version: "3"
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - timetracker-psql:/var/lib/postgresql/data

  timetracker-backend:
    image: guestros/timetracker-backend:latest
    build: ./backend
    container_name: timetracker-backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - PSQL_URL=postgres:postgres@postgres:5432/postgres

  timetracker:
    image: guestros/timetracker:latest
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - timetracker-backend
      - postgres

volumes:
  timetracker-psql: